DROP TABLE IF EXISTS RSS_FREQUENT_ITEMS;
DROP TABLE IF EXISTS RSS_FREQUENT_ITEMS_KEYWORD;

CREATE TABLE RSS_FREQUENT_ITEMS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  link VARCHAR(5000) NOT NULL,
  description VARCHAR(5000) DEFAULT NULL,
  keyword_id INT 
);

CREATE TABLE RSS_FREQUENT_ITEMS_KEYWORD (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  keyword VARCHAR(250) NOT NULL,
  feed_id INT
 );

 CREATE TABLE RSS_FREQUENT_ITEMS_FEED (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  insert_date DATE
 );